### ISSUE TITLE
annotations workflow

### ISSUE THREAD

**Issue by monkeypants** [Tech4Tracing/CartridgeOCR#10]
The current `annotations/` component has the following workflow:
1. download images to a local directory
2. run the annotation tool with reference to the local image directory
3. iterate through the images creating annotations

What we need is multi-user, multi image-set workflow. This ticket is for the design of that workflow, noting:
* sometimes an image will have multiple headstamps in it. For example, if a collector uses a flatbed scanner to capture a collection of (potentially related) headstamps in a single scan.
* sometimes a headstamp image will be captured in a situation that is outside the analysis context, e.g. field work.
* The current tool is designed to annotate "the next non-annotated image" in a set, i.e. work through a set until it is annotated. The task of annotation is expensive in effort, the ergonomics are important.
* When we have a multi-user system, each user may have a collection of image sets (a collection of collections of images), and each image may have multiple headstamps in it.
* The same identical image may be cited in multiple sources - e.g. downloaded from multiple web sites. The same image may be in multiple collections.

Workflow may start with something like this (*part 1: manage images*):
1. authenticate (entity: User)
2. manage image collections (browse, create, edit, delete, search). Entity: ImageCollection
3. within an image collection, manage images (upload, delete/archive, manage image metadata). Entity: Image. Note:
    - m:n cardinality between images and collections
    - image metadata includes 1:n ImageCitation.url, ImageCitation.image_id <-- possibly identified by a content hash
    - do we want to associate taxonomic claims about all headstamps in all images in the collection (e.g. these images are of my collection of shell casings of this caliber, of era, or source, etc). i.e. so individual headstamps can inherit reified metadata from the collection to which they belong (this rule inferred that user made these assertions about this headstamp, because it's in that collection)...
4. the existing ML could identify the coordinates of headstamps within the image. Entity: HeadstampObservation. Note:
    - HeadstampObservation.image_id (same type as ImageCitation.image_id
    - HeadstampObservation.coordinates (where in the image is the headstamp. bounding box x/y? what about affine transformations/ellipses?)
    - which model-version observed this headstamp within the image... Is that something we want to keep track of? If not, how to we manage upgrades to headstamp detection models?

At the end of part 1, we will have a backlog of un-annotated HeadstampObservations, and a process for adding to this backlog. We will want some mechanism for deciding which headstamps to annotate next... (*part 2: manage annotations*):

1. create deterministically-ordered list of HeadstampObservations meeting some criteria
2. for each HeadstampObservation in the list:
    - view it (clipped to HeadstampObservation.coordinates)
    - manage annotations (view existing, add new, edit existing, delete)
    - navigate to the next HeadstampObservation in the list

Note:
* the ability to create "lists of HeadstampObservations meeting some criteria" is a headstamp search. This might have structured features (e.g: from these collections, with/without annotations, of this caliber, manufacturer, age, country of origin, etc) or unstructured features (containing these characters, according to those types of annotation). This API service might be the basis of other UI features - collection browsing, etc.
* In the future, we will have models making "annotations" on HeadstampObserations - e.g. this model-version thinks that glyph is an Arabic character, this person thinks that headstamp is actually the end of a pencil, etc. There will be multiple and various "annotation types", with structured data that's meaning is determined by the annotation type.

**Comment by simra** [comment]
Latest pull request #110 caps off some work to enable collection sharing, and automated headstamp detection on upload.  There are a few outstanding UI annoyances but the e2e workflow is working.

I've probably broken things for the workflow where you don't have the prediction model handy- drop me a note and I'll share the model bits.

**Comment by simra** [comment]
A good deal of this is addressed now so I'll go ahead and close.
