### ISSUE TITLE
Annotation API: Collection management

### ISSUE THREAD

**Issue by monkeypants** [Tech4Tracing/CartridgeOCR#15]
When we have authentication (per #14) and refactored storage (per #13), then we should make a feature that allows authenticated users to create and manage their own image collections.

Image Collections might have titles and notes and some hierarchical browsing ability, but at their simplest a collection needs:
- a name (which collection is it, for human reference - unique for that user)
- an id (globally unique, for machine reference)
- a user ("owner") who controls the collection.
- public/private switch. Is this collection browsable/discoverable by the public, or is it held private (only visible to the owner and t4t algorithms/analysts)
- zero or more images

Note per #10, a collection of images might not be exactly a collection of headstamps. Each image will contain zero or more headstamp images.

**Comment by monkeypants** [comment]
## Manage Collections

* GET /collections?{filter} -> list of collections matching filter (user, public/private, created/updated since/before). The usual paginated "x of y" structure
* POST {data} /collections -> new collection
* GET /collections/{id} -> collection object,
* GET /collections/{id}/images -> list of images (equivalent to GET /images?collection={id})
* PUT {data} /collections/{id} -> updated collection object
* DELETE /collections/{id}

## Manage Images
* POST {image data} /collections/{id} -> data structure including the image id, url, etc.
* GET /images/{id} -> the image. If the collection is public, no auth required. Otherwise (if private) authenticated user must be the collection owner or... (t4t analyst? algorithm service? do we need groups and sharing? Organisations and roles?)
* GET /images/{id}/metadata

Because different sources/collections may have the same image:
* the image {id} could be a content hash
* image metadata could include the list of collections containing this image. Filtered to include public collections and private collections this user has can access.
* images could be fount on web sites (maybe one collection per site, for example). So an image may have a collection of url, first seen, and last seen attributes.
* metadata is contingent on the user.

**Comment by monkeypants** [comment]
This big coarse-grained ticket is mostly done. What do you think is left before we can close it @koriaf ?

**Comment by koriaf** [comment]
Well given it works and users can create collections and upload images - I think it's fine to close; and when we remember something (like "wow how to update collection title") we implement it then
just like you remembered the fact that images shall have "delete" button in the UI and someone is going to implement it
