### ISSUE TITLE
annotations: production-like api container hosting

### ISSUE THREAD

**Issue by monkeypants** [Tech4Tracing/CartridgeOCR#24]
following #12, the current docker-compose runs the annotations api container using a flask development server (`flask run`). For production, we should be running it in a modern rat-free leak-proof WSGI environment (e.g. uvicorn).

This should be fixed with changes to `docker-compose.tml`, `src/annotations/requirements.txt` (and `src/annotation/README.md`),  not change how the local development is run. 

(a `docker-compose build` will be required of course)

**Comment by koriaf** [comment]
just another docker-compose yml file I guess, could be called prod.yml, and splitting requirements to 3 files - base, local and prod

**Comment by simra** [comment]
I don't have a good handle on how things work when we go to azure- we want a persistent SQL db and blob storage- is there a way to docker-compose so those aren't rebuilt from scratch on every deployment?

**Comment by koriaf** [comment]
yes, the data will persisit in the docker-compose if we define volumes and don't delete them (use `docker-compose down` instead of `docker-compose down -v`)
My local data persists between docker-compose runs and rebuilds

**Comment by monkeypants** [comment]
Because our user accounts are invite only, I don't think we should let this block deployments (#43 ). We should just figure out how we want to run the code and do that (Function App? etc), and optimise (swap `flask run` with uvicorn or similar) as part of that, then close this ticket when we make sure we are doing the equivalent thing in our local development composition.

**Comment by simra** [comment]
Aside from migrating to uvicorn I think this issue is wrapped.
