### ISSUE TITLE
annotations: use model to segment headstamps for individual labeling

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#31]

**Comment by monkeypants** [comment]
Does this mean the 1:n relationship between an image and a new entity that represents ‘headstamp detected in the image’?

**Comment by simra** [comment]
Yes, each image may have n headstamps, and each headstamp might have k annotations.

We're going to need some db schema changes and I wonder if we should do the ORM work first.

**Comment by simra** [comment]
Closed with PR #108
