### ISSUE TITLE
add image upload

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#36]

**Comment by monkeypants** [comment]
suggest API `POST {image} /{owner}/{collection}/images`
-> OK if user is collection owner (collection is owned by user), or if user is member of the organization (collection is owned by an organization), or whatever else makes it allowed per #40

So the UI would have an image upload feature (TBD) that allows posting images via the API.

**Comment by simra** [comment]
Completed in api.py
