### ISSUE TITLE
update terraform scripts with annotation tool

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#37]

**Comment by monkeypants** [comment]
I just started looking at this, and the CartridgeOCR terraform script is quite big and non-trivial. 4 storage accounts, a DB, an app, azureml, and the resource groups etc.

Was wondering if maybe we should split the annotation tool and API into it's own repo(s). In a production-like context, it will be an independent bounded context with it's own security groups and policies. The CartridgeOCR will probably mutate at R&D rates of change while the annotation API will be on a shorter path to stability. etc. etc, I don't object to mono-repos, but propose we separate the annotation concern (in support of model development) from the model development, model-based services and end-user application concerns.

Thoughts?

**Comment by simra** [comment]
Sorry for the radio silence, I was out for a week and then missed my notifications.  I think this is a good suggestion and it shouldn't take too much effort to separate the front-end annotation code from the API.

**Comment by koriaf** [comment]
Splitting it to separate repos may get some code duplicated; for example, the code uploading things to Azure storage and downloading it from it

**Comment by monkeypants** [comment]
Given #43 , would you object to us closing this ticket @simra ?

The outcome that matters is "deployed to cloud".
