### ISSUE TITLE
Deploy annotations app to azure

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#43]
@monkeypants @koriaf @simonpo 

Things are coming together really nicely with the annotations tool and I think it would be valuable to start hosting it on an azure endpoint.  I'll take the steps to create an azure subscription for t4t in the next few days, and add you all to the subscription. Could you reach out to me with your microsoft account emails so I can add you to the subscription?

Once the subscription is set up we can coordinate the deployment. I'm not sure of the details here- we may need to provision an SSL cert and I'm not sure if we just target a basic webapp or need to provision something more sophisticated (and add storage, etc). feel free to suggest a configuration.  I'll also migrate my existing google oauth app to accept redirects from the endpoint. -- on this point can you also let me know your google account emails? XD

**Comment by monkeypants** [comment]
Agree! 

It's probably time to set up CI/CD too. I suggest two environments:
* Integration/Test environment, where `main` automatically deploys (after unit tests pass)
* Production environment, where new `*-stable` tags get deployed. I don't think we need a separate "preview" environment at this stage, I think "production is preview" will be appropriate for some time yet.

thoughts?

**Comment by simra** [comment]
Yes, sounds good, my only caution being that we will want to monitor costs and potentially suspend things that aren't in active use.
Also: time for a slack or discord channel?  Teams?

**Comment by monkeypants** [comment]
I voted for slack by creating it, inviting you and making you a co-owner @simra.

I kinda hate Teams, a bit. It never seems to work right for me.

**Comment by simra** [comment]
List of issues we need to close before pushing to public web: #47 #44  (more?)

**Comment by monkeypants** [comment]
I'm currently experimenting with [pulumi](http://pulumi.com) (as an alternative to terraform) for this.

**Comment by monkeypants** [comment]
I don't think we need to let #24 or #44 block this. Our user-accounts are invite only.

**Comment by simra** [comment]
I suspect at some point we're going to run into SSL/TLS headaches. But maybe if we just deploy to Azure ACI and update the google app's callback URL everything will Just Work.
For the time being it might be useful for us each to have our own self-contained deployment for independent testing/hacking.

**Comment by monkeypants** [comment]
IDK what's the best way to deploy the API: Azure Container Instances, Azure Container Apps, Azure Functions, ...? I am currently exploring Azure Container Apps, with a goal to first getting thins working (SQL, running app, static web hosted frontend, CDN over the frontend, app insights, etc) and then get a cloud engineer to review it all and either tell me what I'm doing wrong or (even better) fix it up for me.

WRT self-contained deployments, yep, sure. I'll probably stick with docker-compose for local (pre-commit/PR workflow), then let CI/CD deploy main branch to a "dev" environment when PRs merge (that's the WIP resource groups you might notice appearing and disappearing in the t4t account). As long as the CI/CD scripts are not touching the same things that you are click-opsing in your self-contained deployment we should be fine. Should we use resource groups (in the same subscription) or separate subscriptions to stop then getting entangled?

For SSL/TLS headaches, I guess there's always something :)

I had thought we could manage the google app callback URL from the same pulumi scripts - I'm going to focus on learning how to do the Azure stuff first before thinking about that though.

**Comment by monkeypants** [comment]
I think we can close this because of tech4tracing/t4t-infrastructure
