### ISSUE TITLE
Implement a signup flow

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#47]
This could be very simple:
mailto: link to request access.
We manually add their google account name to a table in the back end.
This unblocks them from authenticating. 

We should have this in place before public deployment.

In the longer term we open up to anyone but I think we need a few more mechanisms in place to prevent abuse and protect users' data.

**Comment by koriaf** [comment]
how do we add it, by API or manually (having SQL access)?

**Comment by simra** [comment]
If we do it via api we'll want to design user scopes first #40 , so only admins can grant access. In the meantime maybe let's do it manually.

**Comment by koriaf** [comment]
to do it manually we must have easy sql access :-)

**Comment by koriaf** [comment]
I can't self-assign it to myself but will spend some time doing it (probably recreating all migrations because user table changes are great and to save time writing custom migration code)
