### ISSUE TITLE
implement a thumbnail cache for browsing collections

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#50]
to avoid loading all images at full resolution.

**Comment by monkeypants** [comment]
I interpreted this to mean post-processing raw images to produce and store thumbnails (either on a just in time basis, or maybe preemptively when images are first uploaded). Probably best to start with jit (if no thumbnail then create it) and then keep it as a guarantee but try to preemptively generated them anyhow (for performance, thumbnails are relatively cheap by definition).

More generally, if we are going to be processing files that people upload, the _first_ step should be a malware scan, before any other code touches them. I'll put that in a different ticket to keep this thing on track.
