### ISSUE TITLE
Move to modern web design workflow

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#61]
We're crossing a threshold where we need to migrate to React or some other reasonable javascript toolchain. Adding simple UI is very fiddly in native JS.  This might be challenging for the custom annotation UX, but other pages should be relatively simple to refactor.

**Comment by monkeypants** [comment]
[this](https://github.com/Tech4Tracing/t4t-annotation-UI) is currently a private repo, but we can make it public when we are happy with it.

**Comment by simra** [comment]
It's been a crazy week- I'll probably have a look at this over the weekend.
