### ISSUE TITLE
Prediction api

### ISSUE THREAD

**Issue by simra** [Tech4Tracing/CartridgeOCR#66]
To start supporting headstamp detection, we need a couple things:
A pointer to a model checkpoint in blob storage, and download to the endpoint at deployment time(?)
Inference code currently found elsewhere in the repo
Versioning story if we want to apply different model versions.
A design for the api. 

Should the prediction api accept image uploads or operate on image ids? Should the predictions be saved to the database and/or cached? 

I'll try to sketch this out more over the weekend.

**Comment by monkeypants** [comment]
This is not my expertise, but what would surprise me least is:

* the prediction API accepts an image and synchronously returns some sort of scorecard 
* the prediction API has model name and version in it's URL
* some agent calls the prediction API and does something with the results (like updating image metadata, not entirely different to making an annotation)

So this agent would update the DB (via the API), the prediction API is ignorant of DB or anything else except itself and the images posted to it.

**Comment by simra** [comment]
I added a PR #77  that gets the basics done and integrates with the old capture app.

> the prediction API has model name and version in it's URL

I think we would configure this in the back-end for the public-facing endpoint.
Maybe we could have a superuser mode to choose any model version.
