### ISSUE TITLE
404 on /static/manifest.json

### ISSUE THREAD

**Issue by monkeypants** [Tech4Tracing/CartridgeOCR#81]
On the current Pulumi playpit deployment at https://container-app31319615.mangomeadow-c4965d06.eastus.azurecontainerapps.io/

The js console seems to be failing to load `/static/manifest.json`

<img width="1427" alt="Screen Shot 2022-06-24 at 10 25 25 pm" src="https://user-images.githubusercontent.com/532596/175534548-17b813fb-16d5-4131-b3e9-4954e319162e.png">

and checking manually...

<img width="1217" alt="Screen Shot 2022-06-24 at 10 26 38 pm" src="https://user-images.githubusercontent.com/532596/175535322-e9fbef7b-3da7-4add-9a38-718da7ae92ac.png">

I am guessing this is a problem, manifest.json sounds important.

**Comment by koriaf** [comment]
it's just a small file which gets generated by `yarn build` in the widget and has been forgotten 
I've fixed it for local setups (see the PR) but someone should probably do it for the Azure one. Just copy the file.

**Comment by monkeypants** [comment]
thanks, PR Merged. @RamParameswaran can you please check this out (and close ticket if OK) on the next deployment

**Comment by RamParameswaran** [comment]
Confirmed that manifest.json is being served.
![image](https://user-images.githubusercontent.com/33742989/175848329-3970dae1-d326-48bd-b333-0a2d155595c3.png)

Closing
