### ISSUE TITLE
big list mischief - discuss solutions

### ISSUE THREAD

**Issue by monkeypants** [Tech4Tracing/CartridgeOCR#82]
so I have a few collections, each with more than a thousand images.

When I start downloading pages and set pagination to 1,000 it works quite well... until it doesn't. Basically the first thousand thumbnails download OK, but somewhere on the second or third page (in quick succession, not at once) it starts to struggle.

<img width="1438" alt="Screen Shot 2022-06-24 at 10 53 32 pm" src="https://user-images.githubusercontent.com/532596/175540391-a0ea6eb0-c869-4d11-b603-1b41a1fc340d.png">

basically the thumbnails stop loading, and the page doesn't recover.

Looking at the replica count in the Azure portal, it seems we are spinning up 10 containers and topping out (if I am reading this correctly)
<img width="1134" alt="Screen Shot 2022-06-24 at 10 58 18 pm" src="https://user-images.githubusercontent.com/532596/175540853-23634ab8-c745-4d48-821c-6cb9b8e1fc0e.png">

That's not a big surprise. The SPA is making a thousand requests at the same time. 

Note that the CPU and RAM are not being hammered - in fact the high water mark is 25% of one core and 80% of the memory working set (125Mb, not much at all). I don't know if this is x10 (per each container) or in total, but either way it's not too much.

I was wondering what we should do about it - it's not a great experience to crash the page and loose some images.

Ideas:
* remove the 1000 images pagination option, that would hide the symptom (and remove the footgun)
* configure/tune things on the Azure side so it doesn't start yielding 503s when it is only getting asked for a few thousand things at once. That might get expensive, if it opens a vector for attacking our wallet...
* push this work onto a static publishing service (rather than the container), possibly with a CDN in front of it. That would be a bit more complex, but delegate DOS prevention to the vendor.
* implement a throttle on the API (429: enhance your calm), so clients are able to fail more gracefully (back-off and retry when told). Won't help in the case of malevolent or inept clients, unless it's a user-specific throttle. Could we implement this through front-door API Gateway, or would the API need to implement this feature?
* the SPA might have a client-side queue and pull down a maximum number of images simultaneously (e.g. 20). That way they would seldom get told to chill out by the server. Woudln't fix load problems from malevolent or inept clients, but would be a gentlemanly compliment to server-side back-off.

What else could we do?

**Comment by monkeypants** [comment]
Also, similar question/discussion for bulk uploads. That would be helped by the "201 uploaded / 200 we arready-gotta-one, but fine whatever" duplicate prevention mentioned else ware, because it would allow the client to harmlessly retry (*), effectively making uploads idempotent. But still, as things are, when I try to bulk upload images the first hundred or so work fine but if I try too many they start to drop some attempts with 503 after maxing-out the container count.

(*) it would also allow confused users to click the upload button more than once without messing up their collection :)

**Comment by RamParameswaran** [comment]
I think this is the main culprit: https://github.com/Tech4Tracing/CartridgeOCR/blob/4bd345a62f425b34203f782adc8da1a5d754b2a4/src/annotation/annotations_app/views/images.py#L237-L246

Instead of sending the actual image data via the Flask app, we should just sent the URL of the object in Azure storage. If we want to apply some access-control logic at the Flask level, we can use [shared access signatures](https://docs.microsoft.com/en-us/rest/api/storageservices/delegate-access-with-shared-access-signature) to provide protected (eg. time restricted) URLS.

**Comment by monkeypants** [comment]
right, "push this work onto a static publishing service (rather than the container)...". Doesn't look too bad e.g. https://stackoverflow.com/questions/41285755/how-do-you-generate-the-signature-for-an-azure-blob-storage-sas-token-in-python

To maintain docker-compose / Azure pairity, the flask app might need to know how it's deployed and pick the right method. Assuming there is already enough environment variables to figure this out (but we might need another switch), maybe it should:
```
if not deployed in azure:
   use the current code
else:
   issue http 302 redirect to the new, specially constructed URL (using a generated SAS token)
```

**Comment by koriaf** [comment]
There is another issue here, the UI retrieves annotations for each image while in the new API version annotation data has already been included in the image endpoint response; so could save some HTTP requests here (many in fact)

I'll implement azure presigned urls as well if we start to have issues with that; it should help a lot

**Comment by simra** [comment]
I think we can close this now. @koriaf do you agree?

**Comment by koriaf** [comment]
Sure
